# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 22:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listener', '0002_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
