# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 22:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listener', '0003_vote_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='time',
            new_name='vote_time',
        ),
    ]
